apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "master01:6443" # Match host alias
networking:
  podSubnet: 192.168.0.0/16 # Match with Calico